In [1]:
from transformers import AutoTokenizer

In [3]:
# 加载编码器
tokenizer = AutoTokenizer.from_pretrained('distilroberta-base')
print(tokenizer)

RobertaTokenizerFast(name_or_path='distilroberta-base', vocab_size=50265, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=False)})


In [4]:
# 编码试算
tokenizer.batch_encode_plus([
    'hide new secretions from the parental units',
    'this moive is great'
])

{'input_ids': [[0, 37265, 92, 3556, 2485, 31, 5, 20536, 2833, 2], [0, 9226, 7458, 2088, 16, 372, 2]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [5]:
# 加载数据
from datasets import load_dataset, load_from_disk

# dataset = load_dataset(path='glue', name='sst2')

dataset = load_from_disk('../data/glue_sst2/')
dataset

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 67349
    })
    validation: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 872
    })
    test: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1821
    })
})

In [9]:
# 对每条数据的sentence部分进行编码
def f(data, tokenizer):
    return tokenizer.batch_encode_plus(data['sentence'])

dataset = dataset.map(f,
           batched=True,
           batch_size=1000,
           num_proc=12,
           remove_columns=['sentence', 'idx', 'label'],
           fn_kwargs={'tokenizer': tokenizer})

Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-e7923d566d2773fc.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-5023b6ee61159e5d.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-d8ecc51bbc907621.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-214f7e5f7775db2c.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-a791525836e67b8f.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-07a89c38c14a9c57.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-493ba12b4f93cfef.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-2683d9b8c4ab1cb5.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-ba6e97660808f56d.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-484ffaa80c36809c.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-20153eb38a336f92.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\train\cache-c1390ad4ff7a5830.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-934391db1a9a06a8.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-ad7f34cfea0a026f.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-d8ecda12cfc1bbd7.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-ddc06be8d6ad1537.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-f1912f7f1cd5e993.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-d863175551f20cd9.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-f4bacd7e635e14e9.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-48fdba2b1cbe65e7.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-0fd5e53407b2e36c.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-495b277a4133902d.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-113266679ce99132.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\validation\cache-879c9e9d60f1da82.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-d947190a8ba2790c.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-560b3729e2faef57.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-2acac187a0cd141b.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-040e97844ff65e6e.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-27ff33537cf80d65.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-198be2e0e17f6071.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-3b2b0db76a462d69.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-e8a6387e5a1e4c1c.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-0662b6798908ec63.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-3e3b2cd1701fe845.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-c52bed55c338752e.arrow


Loading cached processed dataset at D:\AIoT-深度学习视频版\深度学习基础\自然语言处理\NLP入门\data\glue_sst2\test\cache-0fd2fd7c6de4c99c.arrow


In [10]:
# 过滤掉太短的句子
def f(data):
    return [len(i) >= 9 for i in data['input_ids']]

dataset = dataset.filter(f, batched=True, batch_size=1000, num_proc=12)

In [11]:
dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 44279
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 861
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 1776
    })
})

In [12]:
tokenizer.get_vocab()['<mask>']

50264

In [13]:
# 阶段句子, 同时整理成模型需要的格式. 
def f(data):
    b = len(data['input_ids'])
    data['labels'] = data['attention_mask'].copy()
    for i in range(b):
        # 句子长度裁剪到9
        data['input_ids'][i] = data['input_ids'][i][:9]
        data['attention_mask'][i] = [1] * 9
        data['labels'][i] = [-100] * 9
        
        # input_ids最后一位设置为2
        data['input_ids'][i][-1] = 2
        
        # 每一个句子第4个词为mask
        data['labels'][i][4] = data['input_ids'][i][4]
        data['input_ids'][i][4] = 50264
        
    return data

In [42]:
torch.__version__

'1.11.0+cu113'

In [44]:
import transformers
transformers.__version__

'4.26.1'

In [14]:
dataset = dataset.map(f, batched=True, batch_size=1000, num_proc=12)

In [15]:
dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 44279
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 861
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1776
    })
})

In [16]:
dataset['train'][0]

{'input_ids': [0, 37265, 92, 3556, 50264, 31, 5, 20536, 2],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1],
 'labels': [-100, -100, -100, -100, 2485, -100, -100, -100, -100]}

In [17]:
import torch
from transformers.data.data_collator import default_data_collator

In [18]:
loader = torch.utils.data.DataLoader(
    dataset=dataset['train'],
    batch_size=8,
    collate_fn=default_data_collator,
    shuffle=True,
    drop_last=True
)

for data in loader:
    break
len(loader), data

(5534,
 {'input_ids': tensor([[    0,  1264,     9,   475, 50264,     4,  1855,   873,     2],
          [    0,  8155,    34,  1348, 50264,   888,  2609,     5,     2],
          [    0,  2911,  1073,  6796, 50264,    14,   793,  2950,     2],
          [    0,   354,    65,     9, 50264,  5373,  2156,  4281,     2],
          [    0,  2794, 19003,  2787, 50264, 21450,    12, 31549,     2],
          [    0, 29676,    50,    45, 50264,   385,  2401, 14476,     2],
          [    0, 10859,  2156,  1537, 50264, 16016,    66,     5,     2],
          [    0, 19746,    47,   619, 50264,    47,   393,   236,     2]]),
  'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1]]),
  'labels': tensor([[ -100,  -100,  -100,  -10

In [19]:
from transformers import AutoModelForCausalLM, RobertaModel

In [20]:
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.pretrained = RobertaModel.from_pretrained('distilroberta-base')
        
        decoder = torch.nn.Linear(768, tokenizer.vocab_size)
        decoder.bias = torch.nn.Parameter(torch.zeros(tokenizer.vocab_size))
        
        self.fc = torch.nn.Sequential(
            torch.nn.Linear(768, 768),
            torch.nn.GELU(),
            torch.nn.LayerNorm(768, eps=1e-5),
            decoder
        )
        
        # 加载预训练模型的参数
        parameters = AutoModelForCausalLM.from_pretrained('distilroberta-base')
        self.fc[0].load_state_dict(parameters.lm_head.dense.state_dict())
        self.fc[2].load_state_dict(parameters.lm_head.layer_norm.state_dict())
        self.fc[3].load_state_dict(parameters.lm_head.decoder.state_dict())
        
        self.criterion = torch.nn.CrossEntropyLoss()
        
    def forward(self, input_ids, attention_mask, labels=None):
        logits = self.pretrained(input_ids, attention_mask)
        logits = logits.last_hidden_state
        logits = self.fc(logits)
        
        loss = None
        
        if labels is not None:
            shifted_logits = logits[:, :-1].reshape(-1, tokenizer.vocab_size)
            shifted_labels = labels[:, 1:].reshape(-1)
            
            loss = self.criterion(shifted_logits, shifted_labels)
        return {'loss': loss, 'logits': logits}
    

In [21]:
model = Model()

Some weights of the model checkpoint at distilroberta-base were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
If you want to use `RobertaLMHeadModel` as a standalone, add `is_decoder=True.`


In [22]:
# 参数量
print(sum(i.numel() for i in model.parameters()))

121364313


In [23]:
out = model(**data)
out['loss'], out['logits'].shape

(tensor(19.5734, grad_fn=<NllLossBackward0>), torch.Size([8, 9, 50265]))

In [27]:
def test(model):
    model.eval()
    
    loader_test = torch.utils.data.DataLoader(
        dataset = dataset['test'],
        batch_size=8,
        collate_fn=default_data_collator,
        shuffle=True,
        drop_last=True
    )
    
    correct = 0
    total = 0
    
    for i, data in enumerate(loader_test):
        label = data['labels'][:, 4].clone()
        
        # 从数据中抹掉label, 防止模型作弊
        data['labels'] = None
        
        # 计算
        with torch.no_grad():
            out = model(**data)
            
        # out['logits'].shape = [8, 9, 50265] -> [8, 9]
        out = out['logits'].argmax(dim=2)[:, 4]
        correct += (label == out).sum().item()
        total += 8
        
        if i % 10 == 0:
            print(i)
            print(label)
            print(out)
            
        if i == 50:
            break
            
    print('accuracy: ', correct / total)
    
    for i in range(8):
        print(tokenizer.decode(data['input_ids'][i]))
        print(tokenizer.decode(label[i]), tokenizer.decode(out[i]))
        print()

In [28]:
test(model)

0
tensor([  822,  2789, 11783,   408,     9,   241,  1073,    12])
tensor([ 1816, 13536, 30609, 13670,   396,   241, 23250,    12])
10
tensor([ 7590,   117, 29284,  5846,   411,  1116,  2048,  6500])
tensor([ 7590,   117, 29284,  6298,    80,  1116,   403,  7920])
20
tensor([  10,  802,  295, 9760,   77,   16,   10,   28])
tensor([  10, 2813,  218, 9760,   77,   16,   10, 2045])
30
tensor([ 114,   30,  576,  225,   25, 3159,  426, 1346])
tensor([   53,  2156,   576,   814,    25,   543, 25254,  1346])
40
tensor([   16,    10,   172, 15369,   393, 18482,     7,   145])
tensor([ 1241,    10,   172, 41878,    45, 14233,     7,   190])
50
tensor([    5,    29,   480, 10238,   110,     9,    10,  2156])
tensor([  664,    29,  4338, 21844,   239,     9,    98,   878])
accuracy:  0.35294117647058826
<s>the talents of<mask> actors helps ``</s>
 the  young

<s>when it '<mask> all wet,</s>
s s

<s>wait for video<mask> and then do</s>
 --  footage

<s>a tender and<mask> drama, based</s>
 touching

In [29]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [30]:
device

device(type='cuda', index=0)

In [33]:
from transformers import AdamW
from transformers.optimization import get_scheduler


# 训练
def train():
    optimizer = AdamW(model.parameters(), lr=2e-5)
    scheduler = get_scheduler(name='linear',
                             num_warmup_steps=0,
                             num_training_steps=len(loader),
                             optimizer=optimizer)
    model.to(device)
    model.train()
    
    for i, data in enumerate(loader):
        input_ids, attention_mask, labels = data['input_ids'], data['attention_mask'], data['labels']
        input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)
        out = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = out['loss']
        
        loss.backward()
        # 为了训练稳定, 进行梯度裁剪
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        
        optimizer.step()
        scheduler.step()
        
        optimizer.zero_grad()
        model.zero_grad()
        
        if i % 50 == 0:
            label = data['labels'][:, 4].to(device)
            out = out['logits'].argmax(dim=2)[:, 4]
            
            correct = (label == out).sum().item()
            accuracy = correct / 8
            
            lr = optimizer.state_dict()['param_groups'][0]['lr']
            
            print(i, loss.item(), accuracy, lr)

In [34]:
train()

0 18.58106231689453 0.25 1.9996385977593064e-05
50 6.724194049835205 0.125 1.9815684857246115e-05
100 5.237442970275879 0.125 1.963498373689917e-05
150 3.268683910369873 0.5 1.9454282616552225e-05
200 1.94444739818573 0.625 1.927358149620528e-05
250 2.919161319732666 0.625 1.909288037585833e-05
300 3.6054649353027344 0.375 1.8912179255511386e-05
350 2.935434103012085 0.375 1.873147813516444e-05
400 3.1898624897003174 0.25 1.8550777014817495e-05
450 3.477898120880127 0.375 1.8370075894470547e-05
500 2.1842751502990723 0.75 1.81893747741236e-05
550 3.3275065422058105 0.5 1.8008673653776656e-05
600 1.7840290069580078 0.75 1.7827972533429708e-05
650 2.3968780040740967 0.375 1.7647271413082763e-05
700 2.3219566345214844 0.75 1.7466570292735818e-05
750 4.22415828704834 0.25 1.728586917238887e-05
800 2.2510032653808594 0.5 1.7105168052041924e-05
850 2.736297130584717 0.5 1.692446693169498e-05
900 4.031101703643799 0.25 1.674376581134803e-05
950 2.875887870788574 0.5 1.6563064691001085e-05
100

In [36]:
# 保存模型 
torch.save(model, '../data/预测中间词.model')

In [40]:
# 加载模型
model2 = torch.load('../data/预测中间词.model', map_location='cpu')

In [41]:
test(model2)

0
tensor([5712, 2156,  409, 6670,  576,  189,   23,  295])
tensor([5712, 2156,  409,   34,  576,  189,   31,  295])
10
tensor([1481,   98, 5906,  295,    8,   29, 4132,   16])
tensor([ 1481,    98, 34029,   542,     8,    29, 20647,    16])
20
tensor([   19, 11857,  1338,  2624,  9699,     8, 24611,   253])
tensor([   19, 11857,   213,    59,  8745,    13, 42661,   253])
30
tensor([ 992, 2156, 6756,   67,   11,  822,    5,   86])
tensor([992,  30, 705,  10,  41, 822,   5,  86])
40
tensor([  89,   45,    5,   24,  205,   24,   19, 2156])
tensor([ 89,  45,   5,  61, 618,  24,  19,  98])
50
tensor([ 3486,   143,    19, 10713,     5,     5,   668, 32894])
tensor([ 3486,    41,    19, 10713,    10, 44009,   668, 32894])
accuracy:  0.5098039215686274
<s>neither funny<mask> suspenseful nor</s>
 nor  nor

<s>and forget about<mask> attempt at a</s>
 any  an

<s>a film made<mask> as little wit</s>
 with  with

<s>here, ad<mask> lyne comes</s>
rian rian

<s>the fact that<mask> rookie is a</s>
 th